name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: get-version
      run: echo "::set-output name=CURRENT_VERSION::$(cat Makefile | head -n1|awk -F= '{print $2}')"
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: make
      
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.13
      with:
        name: Release v${{ steps.get-version.outputs.CURRENT_VERSION }}
        tag_name: ${{ steps.get-version.outputs.CURRENT_VERSION }}
        draft: true
        prerelease: true

